In [1]:
import pandas as pd
import numpy as np

In [2]:
df_train = pd.read_csv('df_train.csv',low_memory=False, index_col= 0)
df_test = pd.read_csv('df_test.csv',low_memory=False, index_col= 0)

In [3]:
df_train_target = pd.read_csv('df_target_train.csv',low_memory=False)
df_test_target = pd.read_csv('df_target_test.csv',low_memory=False)

In [90]:
df_test_target.shape

(100000, 1)

In [5]:
print(df_train_target.shape, df_train.shape)

(400000, 1) (400000, 294)


In [6]:
inputs_train_with_ref_cat = df_train.loc[: ,['grade:A',
       'grade:B', 'grade:C', 'grade:D', 'grade:E', 'grade:F', 'grade:G',
       'sub_grade:A1', 'sub_grade:A2', 'sub_grade:A3', 'sub_grade:A4',
       'sub_grade:A5', 'sub_grade:B1', 'sub_grade:B2', 'sub_grade:B3',
       'sub_grade:B4', 'sub_grade:B5', 'sub_grade:C1', 'sub_grade:C2',
       'sub_grade:C3', 'sub_grade:C4', 'sub_grade:C5', 'sub_grade:D1',
       'sub_grade:D2', 'sub_grade:D3', 'sub_grade:D4', 'sub_grade:D5',
       'sub_grade:E1', 'sub_grade:E2', 'sub_grade:E3', 'sub_grade:E4',
       'sub_grade:E5', 'sub_grade:F1', 'sub_grade:F2', 'sub_grade:F3',
       'sub_grade:F4', 'sub_grade:F5', 'sub_grade:G1', 'sub_grade:G2',
       'sub_grade:G3', 'sub_grade:G4', 'sub_grade:G5',
       'home_ownership:ANY', 'home_ownership:MORTGAGE',
       'home_ownership:OWN', 'home_ownership:RENT',
       'verification_status:Not Verified',
       'verification_status:Source Verified',
       'verification_status:Verified', 'loan_status:Charged Off',
       'loan_status:Current', 'loan_status:Default',
       'loan_status:Fully Paid', 'loan_status:In Grace Period',
       'loan_status:Late (16-30 days)', 'loan_status:Late (31-120 days)',
       'purpose:car', 'purpose:credit_card', 'purpose:debt_consolidation',
       'purpose:home_improvement', 'purpose:house',
       'purpose:major_purchase', 'purpose:medical', 'purpose:moving',
       'purpose:other', 'purpose:renewable_energy',
       'purpose:small_business', 'purpose:vacation', 'purpose:wedding',
       'addr_state:AK', 'addr_state:AL', 'addr_state:AR', 'addr_state:AZ',
       'addr_state:CA', 'addr_state:CO', 'addr_state:CT', 'addr_state:DC',
       'addr_state:DE', 'addr_state:FL', 'addr_state:GA', 'addr_state:HI',
       'addr_state:ID', 'addr_state:IL', 'addr_state:IN', 'addr_state:KS',
       'addr_state:KY', 'addr_state:LA', 'addr_state:MA', 'addr_state:MD',
       'addr_state:ME', 'addr_state:MI', 'addr_state:MN', 'addr_state:MO',
       'addr_state:MS', 'addr_state:MT', 'addr_state:NC', 'addr_state:ND',
       'addr_state:NE', 'addr_state:NH', 'addr_state:NJ', 'addr_state:NM',
       'addr_state:NV', 'addr_state:NY', 'addr_state:OH', 'addr_state:OK',
       'addr_state:OR', 'addr_state:PA', 'addr_state:RI', 'addr_state:SC',
       'addr_state:SD', 'addr_state:TN', 'addr_state:TX', 'addr_state:UT',
       'addr_state:VA', 'addr_state:VT', 'addr_state:WA', 'addr_state:WI',
       'addr_state:WV', 'addr_state:WY', 'initial_list_status:f',
       'initial_list_status:w', 'addr_state:VT_ID_WV_ME', 'term:36',
       'term:60', 'emp_length_int:0', 'emp_length_int:1',
       'emp_length_int:2_3_4', 'emp_length_int:5', 'emp_length_int:6',
       'emp_length_int:7_8', 'emp_length_int:9', 'emp_length_int:10',
       'int_rate_factor', 'int_rate:<9.59', 'int_rate:9.59-19.006',
       'int_rate:19.006-19.982', 'int_rate:19.982-27.566',
       'int_rate:27.566-28.422', 'int_rate:>28.422', 'annual_inc_factor',
       'annual_inc:<97572', 'annual_inc:>97572',
       'mths_since_last_delinq:missing', 'mths_since_last_delinq:<31.64',
       'mths_since_last_delinq:31.64-76.84',
       'mths_since_last_delinq:>76.84']]

In [7]:
ref_cats = ['grade:G','sub_grade:G5','home_ownership:RENT','verification_status:Not Verified','loan_status:Charged Off','purpose:other','addr_state:UT','initial_list_status:w','emp_length_int:0','int_rate:>28.422','annual_inc:>97572','mths_since_last_delinq:missing']

In [8]:
inputs_train = inputs_train_with_ref_cat.drop(ref_cats,axis=1)

In [10]:
inputs_train = inputs_train.drop(['annual_inc_factor','int_rate_factor'], axis=1)

In [11]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [12]:
reg = LogisticRegression()

In [13]:
reg.fit(inputs_train, df_train_target)

/home/albatrosfirst/credit_risk_model/.venv/lib/python3.10/site-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [14]:
reg.intercept_

array([-1.61839324])

In [15]:
reg.coef_

array([[ 3.27700435e-01, -2.27532910e-01, -3.79934939e-01,
        -3.10731940e-01, -2.46224841e-01, -5.65658905e-01,
         4.24749623e-01,  2.56715496e-01,  5.52044493e-02,
        -1.43414241e-01, -2.65554892e-01,  1.43844382e-03,
         1.19447070e-01, -9.68828802e-02,  1.53799902e-02,
        -2.66915533e-01,  1.71675417e-02, -5.16753152e-02,
        -9.40350270e-02, -1.27713231e-01, -1.23678908e-01,
        -9.40818389e-02, -1.06857609e-01, -1.49717056e-01,
         6.74675749e-02, -2.75430118e-02,  8.91410294e-02,
        -9.40412901e-03, -1.59410861e-01, -6.15611265e-02,
        -1.04989754e-01, -2.77165778e-01, -8.37208668e-02,
        -4.30284644e-02, -7.91724600e-02, -8.25713355e-02,
        -1.51709186e-01, -1.50636122e-03, -4.80499798e-04,
        -1.75085690e-02,  3.31605148e-02, -6.15756988e-02,
        -1.72449845e-01, -3.83225296e-01, -4.56813288e-01,
         1.58244852e+01, -4.87263888e-02,  1.12332627e+01,
         8.31746941e+00,  7.60959064e+00, -7.50909638e+0

In [16]:
feature_name = inputs_train.columns.values

In [17]:
summary_table = pd.DataFrame(columns=['feature_name'], data= feature_name)
summary_table['coefficients'] = np.transpose(reg.coef_)
summary_table.index = summary_table.index +1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()

In [ ]:
summary_table

feature_name  coefficients
0                             Intercept     -1.618393
1                               grade:A      0.327700
2                               grade:B     -0.227533
3                               grade:C     -0.379935
4                               grade:D     -0.310732
..                                  ...           ...
128              int_rate:27.566-28.422     -0.024400
129                   annual_inc:<97572     -0.444224
130       mths_since_last_delinq:<31.64      0.036350
131  mths_since_last_delinq:31.64-76.84      0.000633
132       mths_since_last_delinq:>76.84      0.050857

[133 rows x 2 columns]

***Building Logistic Regression Model with-P Values***

In [ ]:
import scipy.stats as stat

class LogisticRegression_with_pvalues:
    def __init__(self, *args, **kwargs):
          self.model = LogisticRegression(*args,**kwargs)
        
    def fit(self, X, Y):
        self.model.fit(X, Y)
        denom = (2.0 * (1.0 + np.cosh(self.model.decision_function(X))))
        denom = np.tile(denom,(X.shape[1],1)).T
        F_ij = np.dot((X/denom).T, X)
        Cramer_Rao = np.linalg.inv(F_ij)
        sigma_estimates = np.sqrt(np.diagonal(Cramer_Rao))
        z_scores = self.model.coef_[0] / sigma_estimates
        p_values = [stat.norm.sf(abs(x))*2 for x in z_scores]
        self.coef_ = self.model.coef_
        self.intercept_ = self.model.intercept_
        self.p_values = p_values

In [20]:
reg = LogisticRegression_with_pvalues()

In [21]:
reg.fit(inputs_train, df_train_target)

/home/albatrosfirst/credit_risk_model/.venv/lib/python3.10/site-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/tmp/ipykernel_5400/30325308.py:13: RuntimeWarning: invalid value encountered in sqrt
  sigma_estimates = np.sqrt(np.diagonal(Cramer_Rao))


In [22]:
summary_table = pd.DataFrame(columns=['feature_name'], data= feature_name)
summary_table['coefficients'] = np.transpose(reg.coef_)
summary_table.index = summary_table.index +1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

feature_name  coefficients
0                             Intercept     -1.618393
1                               grade:A      0.327700
2                               grade:B     -0.227533
3                               grade:C     -0.379935
4                               grade:D     -0.310732
..                                  ...           ...
128              int_rate:27.566-28.422     -0.024400
129                   annual_inc:<97572     -0.444224
130       mths_since_last_delinq:<31.64      0.036350
131  mths_since_last_delinq:31.64-76.84      0.000633
132       mths_since_last_delinq:>76.84      0.050857

[133 rows x 2 columns]

In [23]:
p_values = reg.p_values

In [24]:
p_values = np.append(np.nan , np.array(p_values))
summary_table['p_values'] = p_values

In [32]:
pd.options.display.max_rows = None
summary_table

feature_name  coefficients       p_values
0                              Intercept     -1.618393            NaN
1                                grade:A      0.327700   1.000000e+00
2                                grade:B     -0.227533   1.000000e+00
3                                grade:C     -0.379935   9.999999e-01
4                                grade:D     -0.310732            NaN
5                                grade:E     -0.246225            NaN
6                                grade:F     -0.565659   1.000000e+00
7                           sub_grade:A1      0.424750   1.000000e+00
8                           sub_grade:A2      0.256715   1.000000e+00
9                           sub_grade:A3      0.055204   1.000000e+00
10                          sub_grade:A4     -0.143414   1.000000e+00
11                          sub_grade:A5     -0.265555   1.000000e+00
12                          sub_grade:B1      0.001438   1.000000e+00
13                          sub_grade:B2      0.119447   1.000000e+00
14                          sub_grade:B3     -0.096883   1.000000e+00
15                          sub_grade:B4      0.015380   1.000000e+00
16                          sub_grade:B5     -0.266916   1.000000e+00
17                          sub_grade:C1      0.017168   1.000000e+00
18                          sub_grade:C2     -0.051675   1.000000e+00
19                          sub_grade:C3     -0.094035   1.000000e+00
20                          sub_grade:C4     -0.127713   1.000000e+00
21                          sub_grade:C5     -0.123679   1.000000e+00
22                          sub_grade:D1     -0.094082            NaN
23                          sub_grade:D2     -0.106858            NaN
24                          sub_grade:D3     -0.149717            NaN
25                          sub_grade:D4      0.067468            NaN
26                          sub_grade:D5     -0.027543            NaN
27                          sub_grade:E1      0.089141            NaN
28                          sub_grade:E2     -0.009404            NaN
29                          sub_grade:E3     -0.159411            NaN
30                          sub_grade:E4     -0.061561            NaN
31                          sub_grade:E5     -0.104990            NaN
32                          sub_grade:F1     -0.277166   1.000000e+00
33                          sub_grade:F2     -0.083721   1.000000e+00
34                          sub_grade:F3     -0.043028   1.000000e+00
35                          sub_grade:F4     -0.079172   1.000000e+00
36                          sub_grade:F5     -0.082571   1.000000e+00
37                          sub_grade:G1     -0.151709   9.687624e-01
38                          sub_grade:G2     -0.001506   9.997392e-01
39                          sub_grade:G3     -0.000480   9.999154e-01
40                          sub_grade:G4     -0.017509   9.971865e-01
41                    home_ownership:ANY      0.033161   9.934790e-01
42               home_ownership:MORTGAGE     -0.061576   7.163473e-01
43                    home_ownership:OWN     -0.172450   4.477133e-01
44   verification_status:Source Verified     -0.383225   2.946546e-02
45          verification_status:Verified     -0.456813   1.804336e-02
46                   loan_status:Current     15.824485  5.354198e-130
47                   loan_status:Default     -0.048726   9.854977e-01
48                loan_status:Fully Paid     11.233263   0.000000e+00
49           loan_status:In Grace Period      8.317469   0.000000e+00
50         loan_status:Late (16-30 days)      7.609591  3.333445e-279
51        loan_status:Late (31-120 days)     -7.509096   8.295601e-02
52                           purpose:car     -0.020546   9.774090e-01
53                   purpose:credit_card      0.006368   9.822284e-01
54            purpose:debt_consolidation     -0.137748   5.802432e-01
55              purpose:home_improvement     -0.169511   6.330184e-01
56                         purpose:hou

In [34]:
inputs_train_with_ref_cat = df_train.loc[: , ['grade:A',
       'grade:B', 'grade:C', 'grade:D', 'grade:E', 'grade:F', 'grade:G',
       'home_ownership:ANY', 'home_ownership:MORTGAGE',
       'home_ownership:OWN', 'home_ownership:RENT',
       'verification_status:Not Verified',
       'verification_status:Source Verified',
       'verification_status:Verified', 'loan_status:Charged Off',
       'loan_status:Current', 'loan_status:Default',
       'loan_status:Fully Paid', 'loan_status:In Grace Period',
       'loan_status:Late (16-30 days)', 'loan_status:Late (31-120 days)',
       'purpose:car', 'purpose:credit_card', 'purpose:debt_consolidation',
       'purpose:home_improvement', 'purpose:house',
       'purpose:major_purchase', 'purpose:medical', 'purpose:moving',
       'purpose:other', 'purpose:renewable_energy',
       'purpose:small_business', 'purpose:vacation', 'purpose:wedding',
       'addr_state:AK', 'addr_state:AL', 'addr_state:AR', 'addr_state:AZ',
       'addr_state:CA', 'addr_state:CO', 'addr_state:CT', 'addr_state:DC',
       'addr_state:DE', 'addr_state:FL', 'addr_state:GA', 'addr_state:HI',
       'addr_state:ID', 'addr_state:IL', 'addr_state:IN', 'addr_state:KS',
       'addr_state:KY', 'addr_state:LA', 'addr_state:MA', 'addr_state:MD',
       'addr_state:ME', 'addr_state:MI', 'addr_state:MN', 'addr_state:MO',
       'addr_state:MS', 'addr_state:MT', 'addr_state:NC', 'addr_state:ND',
       'addr_state:NE', 'addr_state:NH', 'addr_state:NJ', 'addr_state:NM',
       'addr_state:NV', 'addr_state:NY', 'addr_state:OH', 'addr_state:OK',
       'addr_state:OR', 'addr_state:PA', 'addr_state:RI', 'addr_state:SC',
       'addr_state:SD', 'addr_state:TN', 'addr_state:TX', 'addr_state:UT',
       'addr_state:VA', 'addr_state:VT', 'addr_state:WA', 'addr_state:WI',
       'addr_state:WV', 'addr_state:WY', 'initial_list_status:f',
       'initial_list_status:w', 'addr_state:VT_ID_WV_ME', 'term:36',
       'term:60', 'emp_length_int:0', 'emp_length_int:1',
       'emp_length_int:2_3_4', 'emp_length_int:5', 'emp_length_int:6',
       'emp_length_int:7_8', 'emp_length_int:9', 'emp_length_int:10',
       'int_rate_factor', 'int_rate:<9.59', 'int_rate:9.59-19.006',
       'int_rate:19.006-19.982', 'int_rate:19.982-27.566',
       'int_rate:27.566-28.422', 'int_rate:>28.422', 'annual_inc_factor',
       'annual_inc:<97572', 'annual_inc:>97572',
       'mths_since_last_delinq:missing', 'mths_since_last_delinq:<31.64',
       'mths_since_last_delinq:31.64-76.84',
       'mths_since_last_delinq:>76.84']]

In [35]:
ref_cats = ['grade:G','home_ownership:RENT','verification_status:Not Verified','loan_status:Charged Off','purpose:other','addr_state:UT','initial_list_status:w','emp_length_int:0','int_rate:>28.422','annual_inc:>97572','mths_since_last_delinq:missing']

In [53]:
inputs_train = inputs_train_with_ref_cat.drop(ref_cats,axis=1)
inputs_train = inputs_train.drop(['annual_inc_factor','int_rate_factor'], axis=1)
inputs_train.head()

grade:A  grade:B  grade:C  grade:D  grade:E  grade:F  home_ownership:ANY  \
id                                                                              
NaN        1        0        0        0        0        0                   0   
NaN        0        1        0        0        0        0                   0   
NaN        1        0        0        0        0        0                   0   
NaN        1        0        0        0        0        0                   0   
NaN        0        1        0        0        0        0                   0   

     home_ownership:MORTGAGE  home_ownership:OWN  \
id                                                 
NaN                        1                   0   
NaN                        0                   0   
NaN                        1                   0   
NaN                        1                   0   
NaN                        1                   0   

     verification_status:Source Verified  verification_status:Verified  \
id                                                                       
NaN                                    1                             0   
NaN                                    1                             0   
NaN                                    0                             1   
NaN                                    1                             0   
NaN                                    1                             0   

     loan_status:Current  loan_status:Default  loan_status:Fully Paid  \
id                                                                      
NaN                    0                    0                       1   
NaN                    0                    0                       0   
NaN                    1                    0                       0   
NaN                    1                    0                       0   
NaN                    1                    0                       0   

     loan_status:In Grace Period  loan_status:Late (16-30 days)  \
id                                                                
NaN                            0                              0   
NaN                            0                              0   
NaN                            0                              0   
NaN                            0                              0   
NaN                            0                              0   

     loan_status:Late (31-120 days)  purpose:car  purpose:credit_card  \
id                                                                      
NaN                               0            0                    1   
NaN                               1            0                    0   
NaN                               0            0                    1   
NaN                               0            0                    0   
NaN                               0            0                    1   

     purpose:debt_consolidation  purpose:home_improvement  purpose:house  \
id                                                                         
NaN                           0                         0              0   
NaN                           0                         0              0   
NaN                           0                         0              0   
NaN                           1                         0              0   
NaN                           0                         0              0   

     purpose:major_purchase  purpose:medical  purpose:moving  \
id                                                             
NaN                       0                0               0   
NaN                       1                0               0   
NaN                       0                0               0   
NaN                       0                0               0   
NaN                       0                0               0   

     purpose:renewable_energy  purpose:small_business  purpose:vacation  \
id

In [59]:
reg2 = LogisticRegression_with_pvalues()
reg2.fit(inputs_train, df_train_target)

/home/albatrosfirst/credit_risk_model/.venv/lib/python3.10/site-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [60]:
feature_name = inputs_train.columns.values

In [61]:
summary_table = pd.DataFrame(columns=['feature_name'], data= feature_name)
summary_table['coefficients'] = np.transpose(reg2.coef_)
summary_table.index = summary_table.index +1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

feature_name  coefficients
0                             Intercept     -1.618393
1                               grade:A      0.288041
2                               grade:B     -0.239608
3                               grade:C     -0.308552
4                               grade:D     -0.220026
5                               grade:E     -0.273900
6                               grade:F     -0.614081
7                    home_ownership:ANY      0.033227
8               home_ownership:MORTGAGE     -0.040319
9                    home_ownership:OWN     -0.191590
10  verification_status:Source Verified     -0.439442
11         verification_status:Verified     -0.477200
12                  loan_status:Current     15.636086
13                  loan_status:Default     -0.047901
14               loan_status:Fully Paid     11.357543
15          loan_status:In Grace Period      8.286627
16        loan_status:Late (16-30 days)      7.110247
17       loan_status:Late (31-120 days)     -7.458775
18                          purpose:car     -0.016599
19                  purpose:credit_card     -0.013393
20           purpose:debt_consolidation     -0.071885
21             purpose:home_improvement     -0.164381
22                        purpose:house     -0.100080
23               purpose:major_purchase     -0.305181
24                      purpose:medical     -0.194896
25                       purpose:moving     -0.033859
26             purpose:renewable_energy      0.024842
27               purpose:small_business     -0.240687
28                     purpose:vacation     -0.038046
29                      purpose:wedding     -0.005841
30                        addr_state:AK      0.021872
31                        addr_state:AL     -0.131795
32                        addr_state:AR     -0.049801
33                        addr_state:AZ     -0.068938
34                        addr_state:CA     -0.272792
35                        addr_state:CO     -0.070654
36                        addr_state:CT      0.103228
37                        addr_state:DC      0.037227
38                        addr_state:DE     -0.017097
39                        addr_state:FL     -0.182744
40                        addr_state:GA      0.040780
41                        addr_state:HI     -0.036556
42                        addr_state:ID      0.054178
43                        addr_state:IL      0.098726
44                        addr_state:IN     -0.047701
45                        addr_state:KS      0.005413
46                        addr_state:KY      0.015666
47                        addr_state:LA      0.014561
48                        addr_state:MA     -0.037181
49                        addr_state:MD     -0.046662
50                        addr_state:ME      0.061269
51                        addr_state:MI      0.014226
52                        addr_state:MN     -0.077968
53                        addr_state:MO     -0.191275
54                        addr_state:MS     -0.011540
55                        addr_state:MT      0.027057
56                        addr_state:NC     -0.205248
57                        addr_state:ND      0.003791
58                        addr_state:NE     -0.091421
59                        addr_state:NH      0.025689
60                        addr_state:NJ      0.047913
61                        addr_state:NM     -0.017614
62                        addr_state:NV     -0.226625
63                        addr_state:NY     -0.186871
64                        addr_state:OH      0.031040
65                        addr_state:OK     -0.094600
66                        addr_state:OR      0.135346
67                        addr_state:PA     -0.021447
68                        addr_state:RI      0.018422
69                        addr_state:SC     -0.030223
70                        addr_state:SD     -0.046264
71                        addr_state:TN     -0.014699
72                        addr_state:TX     -0.182242
73                        addr_

In [62]:
p_values = np.append(np.nan , np.array(reg2.p_values))
summary_table['p_values'] = p_values

***Model Validation***

In [63]:
inputs_test_with_ref_cat = df_test.loc[:, ['grade:A',
       'grade:B', 'grade:C', 'grade:D', 'grade:E', 'grade:F', 'grade:G',
       'home_ownership:ANY', 'home_ownership:MORTGAGE',
       'home_ownership:OWN', 'home_ownership:RENT',
       'verification_status:Not Verified',
       'verification_status:Source Verified',
       'verification_status:Verified', 'loan_status:Charged Off',
       'loan_status:Current', 'loan_status:Default',
       'loan_status:Fully Paid', 'loan_status:In Grace Period',
       'loan_status:Late (16-30 days)', 'loan_status:Late (31-120 days)',
       'purpose:car', 'purpose:credit_card', 'purpose:debt_consolidation',
       'purpose:home_improvement', 'purpose:house',
       'purpose:major_purchase', 'purpose:medical', 'purpose:moving',
       'purpose:other', 'purpose:renewable_energy',
       'purpose:small_business', 'purpose:vacation', 'purpose:wedding',
       'addr_state:AK', 'addr_state:AL', 'addr_state:AR', 'addr_state:AZ',
       'addr_state:CA', 'addr_state:CO', 'addr_state:CT', 'addr_state:DC',
       'addr_state:DE', 'addr_state:FL', 'addr_state:GA', 'addr_state:HI',
       'addr_state:ID', 'addr_state:IL', 'addr_state:IN', 'addr_state:KS',
       'addr_state:KY', 'addr_state:LA', 'addr_state:MA', 'addr_state:MD',
       'addr_state:ME', 'addr_state:MI', 'addr_state:MN', 'addr_state:MO',
       'addr_state:MS', 'addr_state:MT', 'addr_state:NC', 'addr_state:ND',
       'addr_state:NE', 'addr_state:NH', 'addr_state:NJ', 'addr_state:NM',
       'addr_state:NV', 'addr_state:NY', 'addr_state:OH', 'addr_state:OK',
       'addr_state:OR', 'addr_state:PA', 'addr_state:RI', 'addr_state:SC',
       'addr_state:SD', 'addr_state:TN', 'addr_state:TX', 'addr_state:UT',
       'addr_state:VA', 'addr_state:VT', 'addr_state:WA', 'addr_state:WI',
       'addr_state:WV', 'addr_state:WY', 'initial_list_status:f',
       'initial_list_status:w', 'addr_state:VT_ID_WV_ME', 'term:36',
       'term:60', 'emp_length_int:0', 'emp_length_int:1',
       'emp_length_int:2_3_4', 'emp_length_int:5', 'emp_length_int:6',
       'emp_length_int:7_8', 'emp_length_int:9', 'emp_length_int:10',
       'int_rate_factor', 'int_rate:<9.59', 'int_rate:9.59-19.006',
       'int_rate:19.006-19.982', 'int_rate:19.982-27.566',
       'int_rate:27.566-28.422', 'int_rate:>28.422', 'annual_inc_factor',
       'annual_inc:<97572', 'annual_inc:>97572',
       'mths_since_last_delinq:missing', 'mths_since_last_delinq:<31.64',
       'mths_since_last_delinq:31.64-76.84',
       'mths_since_last_delinq:>76.84']]

In [64]:
inputs_test_with_ref_cat.columns

Index(['grade:A', 'grade:B', 'grade:C', 'grade:D', 'grade:E', 'grade:F',
       'grade:G', 'home_ownership:ANY', 'home_ownership:MORTGAGE',
       'home_ownership:OWN',
       ...
       'int_rate:19.982-27.566', 'int_rate:27.566-28.422', 'int_rate:>28.422',
       'annual_inc_factor', 'annual_inc:<97572', 'annual_inc:>97572',
       'mths_since_last_delinq:missing', 'mths_since_last_delinq:<31.64',
       'mths_since_last_delinq:31.64-76.84', 'mths_since_last_delinq:>76.84'],
      dtype='object', length=111)

In [71]:
input_test = inputs_test_with_ref_cat.drop(ref_cats, axis = 1)
input_test = input_test.drop(['int_rate_factor', 'annual_inc_factor'], axis = 1)
input_test.head()

grade:A  grade:B  grade:C  grade:D  grade:E  grade:F  home_ownership:ANY  \
id                                                                              
NaN        0        1        0        0        0        0                   0   
NaN        1        0        0        0        0        0                   0   
NaN        0        0        0        1        0        0                   0   
NaN        0        1        0        0        0        0                   0   
NaN        0        0        0        1        0        0                   0   

     home_ownership:MORTGAGE  home_ownership:OWN  \
id                                                 
NaN                        0                   0   
NaN                        0                   0   
NaN                        1                   0   
NaN                        1                   0   
NaN                        0                   0   

     verification_status:Source Verified  verification_status:Verified  \
id                                                                       
NaN                                    1                             0   
NaN                                    0                             0   
NaN                                    0                             0   
NaN                                    0                             1   
NaN                                    1                             0   

     loan_status:Current  loan_status:Default  loan_status:Fully Paid  \
id                                                                      
NaN                    1                    0                       0   
NaN                    1                    0                       0   
NaN                    1                    0                       0   
NaN                    1                    0                       0   
NaN                    1                    0                       0   

     loan_status:In Grace Period  loan_status:Late (16-30 days)  \
id                                                                
NaN                            0                              0   
NaN                            0                              0   
NaN                            0                              0   
NaN                            0                              0   
NaN                            0                              0   

     loan_status:Late (31-120 days)  purpose:car  purpose:credit_card  \
id                                                                      
NaN                               0            0                    1   
NaN                               0            0                    1   
NaN                               0            0                    0   
NaN                               0            0                    0   
NaN                               0            0                    1   

     purpose:debt_consolidation  purpose:home_improvement  purpose:house  \
id                                                                         
NaN                           0                         0              0   
NaN                           0                         0              0   
NaN                           0                         1              0   
NaN                           0                         1              0   
NaN                           0                         0              0   

     purpose:major_purchase  purpose:medical  purpose:moving  \
id                                                             
NaN                       0                0               0   
NaN                       0                0               0   
NaN                       0                0               0   
NaN                       0                0               0   
NaN                       0                0               0   

     purpose:renewable_energy  purpose:small_business  purpose:vacation  \
id

In [72]:
y_hat_test = reg2.model.predict(input_test)

In [78]:
y_hat_test

array([1, 1, 1, ..., 1, 1, 1], shape=(100000,))

In [79]:
y_hat_test_prob = reg2.model.predict_proba(input_test)

In [80]:
y_hat_test_prob

array([[5.88505001e-06, 9.99994115e-01],
       [2.45742238e-06, 9.99997543e-01],
       [2.76633693e-06, 9.99997234e-01],
       ...,
       [5.18854731e-06, 9.99994811e-01],
       [9.12339109e-06, 9.99990877e-01],
       [1.33875912e-05, 9.99986612e-01]], shape=(100000, 2))

In [81]:
y_hat_test_prob[: ][: ,1]

array([0.99999411, 0.99999754, 0.99999723, ..., 0.99999481, 0.99999088,
       0.99998661], shape=(100000,))

In [82]:
y_hat_test_prob = y_hat_test_prob[: ][: ,1]

In [84]:
y_hat_test_prob

array([0.99999411, 0.99999754, 0.99999723, ..., 0.99999481, 0.99999088,
       0.99998661], shape=(100000,))

In [98]:
from sklearn.metrics import roc_auc_score, accuracy_score, confusion_matrix, roc_curve

In [95]:
acc = accuracy_score(df_test_target,y_hat_test)
acc

1.0

In [94]:
roc_score = roc_auc_score(df_test_target,y_hat_test)
roc_score

np.float64(1.0)

In [97]:
matrix = confusion_matrix(df_test_target,y_hat_test)
matrix

array([[ 2841,     0],
       [    0, 97159]])